"""RECOVERY.md, generated from core.recovery.

Deliberately not a section of METRICS.md. That file is frozen and every number
in it was measured against a generated world; every per-channel rate here is
asserted, because the dataset records payments and not outreach. Putting them
in one document would quietly launder one kind of number into the other. This
one stands beside it, says what it is in its first line, and changes nothing in
the frozen file.

    python run.py recovery
"""
from __future__ import annotations

from dataclasses import replace

from .recovery import (BY_KEY, CHANNELS, RECONTACT_ANCHOR_BOTTOM,
                       RECONTACT_ANCHOR_TOP, RecoveryConfig, crossover_table,
                       grade, p_return, sweep)


def to_markdown(ledger, cfg: RecoveryConfig = RecoveryConfig()) -> str:
    o = grade(ledger, cfg)
    singles = {k: grade(ledger, cfg, only=k).blended_rate
               for k in ("sms", "email", "voice", "human")}
    L: list = []
    w = L.append

    w("# RECOVERY\n")
    w(f"Generated by `python run.py recovery`. {cfg.label()}.\n")
    w("**This file is not METRICS.md and its numbers are not of the same kind.**")
    w("Every figure in METRICS.md was measured. Every per-channel rate here is")
    w("asserted, because the dataset records payments and not outreach. They are")
    w("kept apart so one cannot be mistaken for the other, and METRICS.md is")
    w("unchanged by any of this.\n")

    w("## 1. Why there is a second decision\n")
    w("Reversing a block recovers nothing on its own. A corrected row in a database")
    w("is not a sale: the customer has gone, and somebody has to go and get them.")
    w("That is a separate expected-value question with its own arithmetic.\n")
    w("```")
    w("EV(channel) = P(return | channel, elapsed) * V  -  cost(channel)")
    w("```\n")
    w("`V` is the conversion value, and it is exactly the `EV(release)` the policy")
    w("already computed. The fraud risk is therefore priced once, in the release")
    w("decision, and not counted a second time here.\n")

    w("## 2. The channels\n")
    w("| Channel | Cost | Arrives in | Reaches | Of those, return | P(return) | Two-way |")
    w("|---|---|---|---|---|---|---|")
    for c in CHANNELS:
        cost = "free" if c.cost_inr == 0 else f"Rs {c.cost_inr:,.2f}"
        w(f"| {c.name} | {cost} | {c.latency_min:.0f} min | {c.reach:.0%} | "
          f"{c.lift:.0%} | {p_return(c, 0, cfg):.1%} | "
          f"{'yes' if c.two_way else 'no'} |")
    w("")
    w("A voice agent is not a better nudge than an SMS. It converts worse and costs")
    w("forty times as much. It is here because it is the cheapest channel that can")
    w("ask a question and hear the answer, and a step-up is a question.\n")

    w("## 3. The crossovers\n")
    w("Every rate above is asserted. A crossover is not a rate: it is the case value")
    w("at which one channel overtakes another, and it can be checked against")
    w("whatever a pilot actually measures. Quote these rather than the rates, for")
    w("the same reason METRICS.md 11 leads with a breakeven rather than a point in")
    w("its band.\n")
    w("| Dearer channel | Overtakes | Above a case value of |")
    w("|---|---|---|")
    rows = [(a, b, v) for a, b, v in crossover_table(cfg) if v != float("inf")]
    for a, b, v in sorted(rows, key=lambda r: r[2]):
        w(f"| {BY_KEY[a].name} | {BY_KEY[b].name} | Rs {v:,.0f} |")
    w("")
    w("Every pair not listed never crosses over at any value. An SMS is both cheaper")
    w("and better converting than a phone call, so no order is ever large enough to")
    w("make the call the better nudge.\n")

    w("## 4. Time\n")
    w(f"Half-life {cfg.half_life_min:,.0f} minutes, which is one day. **This is not a")
    w("free parameter.** METRICS.md 11 fixed two points on this curve when it")
    w(f"published the {RECONTACT_ANCHOR_TOP:.0%} to {RECONTACT_ANCHOR_BOTTOM:.0%} band")
    w("and called its ends an in-session retry prompt and a next-day email. Exactly")
    w("one exponential passes through both and its half-life is 1438 minutes. If the")
    w("frozen band is right then this is right, and if it is wrong then both are")
    w("wrong together, which is the correct way for two documents to depend on each")
    w("other.\n")
    w("| Programme | Here | METRICS.md 11 |")
    w("|---|---|---|")
    w(f"| SMS only, arrives in two minutes | {singles['sms']:.1%} | "
      f"{RECONTACT_ANCHOR_TOP:.0%}, \"an in-session retry prompt\" |")
    w(f"| Email only, lands next day | {singles['email']:.1%} | "
      f"{RECONTACT_ANCHOR_BOTTOM:.0%}, \"a next-day email\" |")
    w(f"| **The ladder, every rung** | **{o.blended_rate:.1%}** | - |")
    w("")
    w("Two documents disagreeing here would mean one of them was wrong. A test")
    w("asserts they do not.\n")

    w("## 5. Over the blocked pile\n")
    w("| | |")
    w("|---|---|")
    w(f"| Cases actioned | {o.contacted:,} of {o.cases:,} |")
    w(f"| Left alone | {o.uncontacted:,}, which is exactly the upheld blocks |")
    w(f"| Expected to return | {o.expected_returns:,.0f} ({o.blended_rate:.1%}) |")
    w(f"| Outreach spend | Rs {o.spend_inr:,.0f} |")
    w(f"| Spend per customer recovered | "
      f"Rs {o.spend_inr / max(1, o.expected_returns):,.2f} |")
    w(f"| Median time from block to money | {o.median_eta_min:,.0f} min |")
    w(f"| Reviewer time | {o.human_minutes / 60:,.0f} hours over {o.days} days |")
    w("")
    w("| Channel | Attempts | Spend | Expected returns |")
    w("|---|---|---|---|")
    for r in o.rows():
        w(f"| {BY_KEY[r['channel']].name} | {r['cases']:,} | "
          f"Rs {r['spend_inr']:,.0f} | {r['expected_returns']:,.1f} |")
    w("")
    w("Everything the system did not uphold is actioned. An overturn always has")
    w("positive expected value to chase, and a step-up or an escalation is contacted")
    w("because the policy already decided an exchange was warranted. So nothing goes")
    w("quietly missing between the decision and the outreach.\n")

    w("## 6. A person is rationed by time, not by money\n")
    w(f"A Rs {BY_KEY['human'].cost_inr:,.0f} callback pays for itself on nearly any")
    w("case worth chasing, so cost is not what limits it. People are. This is the")
    w("argument METRICS.md 2 makes about the reviewer baseline, applied to outreach;")
    w("leaving it out would have rebuilt the exact fantasy that section punctures.\n")
    w("| Callbacks per day | Denied a person | Stranded | Spend | Expected returns |")
    w("|---|---|---|---|---|")
    for n in (4, 12, 40, 10_000):
        t = grade(ledger, replace(cfg, human_calls_per_day=n))
        label = f"{n:,}" if n < 1000 else "unlimited"
        w(f"| {label} | {t.human_denied:,} | {t.stranded} | Rs {t.spend_inr:,.0f} | "
          f"{t.expected_returns:,.0f} |")
    w("")
    w(f"At the shipped budget this supports {o.supports_per_day:,.0f} blocked orders a")
    w(f"day before rationing starts, and this merchant set produces "
      f"{o.cases / o.days:,.0f}. So capacity does not bind here, which is reported")
    w("rather than assumed away.\n")
    w("A denied escalation is **stranded**, not merely handled more cheaply. An")
    w("escalation's only permitted channel is a person, so running out of people")
    w("means nobody looks at the case at all. It is counted separately for that")
    w("reason, because burying it in the same total as the cases the ladder chose to")
    w("leave alone would hide the one outcome that should never be silent.\n")

    w("## 7. What is asserted\n")
    w("Every per-channel rate in section 2. Two of them lean pessimistic on purpose:\n")
    w(f"- Second and third rungs are shrunk by {cfg.rung_correlation:.0%}, because")
    w("  somebody who ignores an SMS is likelier than average to ignore a call too.")
    w("- The value of the customer relationship at risk is left out entirely unless")
    w("  switched on, because it rests on a churn rate nobody has measured.\n")
    w("Relaxing either only improves the result, so what is reported is a floor and")
    w("not a midpoint.\n")
    w("| Half-life | Rung correlation | Expected to return | Spend | Median time |")
    w("|---|---|---|---|---|")
    for r in sweep(ledger):
        w(f"| {r['half_life_min']:,.0f} min | {r['rung_correlation']:.2f} | "
          f"{r['blended_rate']:.1%} | Rs {r['spend_inr']:,.0f} | "
          f"{r['median_eta_min']:,.0f} min |")
    w("")
    return "\n".join(L)
